### ISSUE TITLE
Change 'group' => t('User') to 'group' => t('User account')?

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/realname#11]
Per [this issue in Rules module](https://github.com/backdrop-contrib/rules/issues/196), the Rules module is changing the name of the "User" group to "User account" to be consistent with Backdrop terminology.

The corresponding change in this module would in `realname_rules_action_info()`, change the group name as well for `user-realname_update" action.

**Comment by indigoxela** [comment]
@bugfolder many thanks for notifying!

When will this change in Rules get released?

**Comment by bugfolder** [comment]
> When will this change in Rules get released?

Soon as I can get co-maintainer review on the PR from @argiepiano or @laryn (or you or @olafgrabienski, of course!).

**Comment by bugfolder** [comment]
Change has been released:

https://github.com/backdrop-contrib/rules/releases/tag/1.x-2.3.4

**Comment by bugfolder** [comment]
PR added.

**Comment by indigoxela** [comment]
> PR added.

Wow, that's a service. :smiley: PR merged, release coming soon.
