### ISSUE TITLE
Settings link to email templates is wrong

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/realname#13]
**Steps to reproduce**

1. Go to Real Name settings (`admin/config/people/realname`)
2. Under _Advanced settings_ > _Suppress missing token warning in e-mail templates_  within the help text for this setting, click on the email link.

**Expected result**
Goes to email template page - `admin/config/people/emails`
![image](https://github.com/backdrop-contrib/realname/assets/20357797/6f1dfe48-606b-41a8-9e13-ed95bf04b092)

**Actual**
Goes to `admin/config/people/accounts#edit-email-admin-created` which doesn't exist so goes to `admin/config/people`
![chrome_ffYr9K7Oc2](https://github.com/backdrop-contrib/realname/assets/20357797/46fa938b-533d-4352-93fa-6e57b8633adb)

**Comment by indigoxela** [comment]
@yorkshire-pudding sorry, I totally missed this report. :pleading_face:

Here's a [PR](https://github.com/backdrop-contrib/realname/pull/15) that fixes the url.
