### ISSUE TITLE
Do not display the 'Real name:' field for users who prefer not to set one

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/realname#3]
User profiles show the 'Real name:' field regardless if realname is set or not. I believe the field must be shown only for users who decided to set their real names.

**Comment by indigoxela** [comment]
> User profiles show the 'Real name:' field regardless if realname is set or not.

Hm, the "Real name" field is a pseudo-field. I'm not sure yet, how to add an extra setting on field UI to "hide if empty"...

**Comment by indigoxela** [comment]
Another thought: maybe it's easier if you hide the "Real name" field completely and instead display the field, which is the source of the real name? - That should be a regular field with display options.

**Comment by alanmels** [comment]
> Another thought: maybe it's easier if you hide the "Real name" field completely and instead display the field, which is the source of the real name? - That should be a regular field with display options.

Didn't initially think of that option. Thanks for the hint and let's close this one.
