### ISSUE TITLE
Can cause php notices (?)

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/realname#4]
It's not fully clear yet, but under some circumstances this module can cause php notices on user pages if other modules use hook_preprocess_field().

`Notice: Undefined index: #formatter in FOOMODULE_preprocess_field()...`

Might need some digging.

**Comment by yorkshire-pudding** [comment]
Possibly related - this warning (PHP 8.1):

> Warning: Trying to access array offset on value of type null in field_formatter_settings_get_instance_display_settings() (line 612 of /app/docroot/core/modules/field/field.info.inc)

on trying to load user page.

I have field wrappers module which is using that function and the warning disappears if I disable that module.

**Comment by indigoxela** [comment]
Hey @yorkshire-pudding,

I can confirm that installing the field_wrappers module causes warnings on the user page. But different ones than initially reported.

However, this odd pseudo field rendering approach has always baffled me: https://github.com/backdrop-contrib/realname/blob/1.x-1.x/realname.module#L175

And that's the code causing the problem with field_wrappers, which assumes this pseudo field to provide real data.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop-contrib/realname/pull/14) is available for testing.

It mimics theme_field() without actually calling it. That should be backwards compatible.

**Comment by argiepiano** [comment]
> However, this odd pseudo field rendering approach has always baffled me:

I've seen this approach before - using theme_field to render entity properties. The benefit of this is that it can be more easily overridden, both as a theming function or through templates. If you decided to keep this as it was (instead of writing new code to theme this), the only thing needed (missing) is including `'#formatter' => 'text_default'` in the build array for the realname "field".

**Comment by indigoxela** [comment]
@argiepiano merry Christmas! :christmas_tree: 

> I've seen this approach before

That doesn't necessarily mean, it's a good idea. :wink: 

> ... the only thing needed (missing) is including '#formatter' => 'text_default'

That doesn't fix the PHP warnings on the account page.

IMO this field theme abuse for the "realname" pseudo field shouldn't happen at all. I don't think it's currently possible to override the hardcoded output, anyway, as the field theme doesn't do the actual rendering.

The current PR does it more like the "Member for" info does it. Still hardcoded, but not abusing the field theme.

**Comment by indigoxela** [comment]
Oops, it *is* possible to use a template file named `field--realname.tpl.php`. Never tried that before.

If we have to keep that, I've no idea how to fix the PHP warnings. :shrug:

**Comment by indigoxela** [comment]
Took another, and closer look...

@yorkshire-pudding I don't think, there's something _this_ module can do without introducing breaking changes.

I'd suggest to report the problem with pseudo-fields in the field_wrappers module queue. It seems to me that in field_wrappers_preprocess_field() there should be some check for pseudo fields, which have neither formatter settings, nor even a field instance. This is also relevant for other pseudo fields.

**Comment by yorkshire-pudding** [comment]
Thanks @argiepiano and @indigoxela - I've raised [an issue](/backdrop-contrib/field_wrappers/issues/12) on the Field Wrappers module.

**Comment by yorkshire-pudding** [comment]
@indigoxela - I appreciate you're not planning to implement the [PR](#14) as it is not backward compatible, but as I'm not using that template, and as there is no solution forthcoming for Field Wrappers (I've had a look and got no ideas how to detect a pseudo field), I've applied the patch and it gets rid of the warning.

**Comment by indigoxela** [comment]
I'm still hoping for a better solution, but currently ran out of ideas. I totally understand, that you need a solution sooner, and prefer the patch for now.

**Comment by argiepiano** [comment]
As suggested by @indigoxela, I think the fix for field_wrapper should be pretty simple and makes sense. That module assumes that, because an element uses `theme_field()`, it's a Field API field, which is not always true.

**Comment by yorkshire-pudding** [comment]
@indigoxela - I know the fix in field_wrappers fixes my use case, but does it fix this?

> It's not fully clear yet, but under some circumstances this module can cause php notices on user pages if other modules use hook_preprocess_field().
> 
> `Notice: Undefined index: #formatter in FOOMODULE_preprocess_field()...`
> 
> Might need some digging.

**Comment by indigoxela** [comment]
> I know the fix in field_wrappers fixes my use case, but does it fix this?

Depends on how that FOOMODULE_preprocess_field() is implemented, I guess.

**Comment by argiepiano** [comment]
There are a few contrib modules that check for $variables['element']['#formatter'] within their implementation of `hook_preprocess_field()`, or inside `hook_field_attach_view_alter()`. See for example `imagewebp`.

In those cases, you'll see this warning because the build array provided by realname does not specify a formatter, and the field API engine will not provide a default_formatter because the build array is already built (by realname). The solution, as I said above, is to provide a value for `'#formatter' => 'text_default',`  in the build array.

**Comment by argiepiano** [comment]
PR provided: #19

**Comment by argiepiano** [comment]
> That doesn't fix the PHP warnings on the account page.

To clarify, my solution did not intend to fix the problem with field_wrapper (the problem had a different origin), but it will fix the problem with those contrib modules that check for `#formatter` in their hook_preprocess_field().

**Comment by indigoxela** [comment]
@argiepiano many thanks for digging into this. Makes a lot of sense. :+1: 

With the imagewebp installed, this patch fixes one out of four notices. Better than nothing, though. Mystery solved. :wink: The rest of notices is caused by field_wrappers in its unpatched version.
