### ISSUE TITLE
Database not removed on uninstall

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/realname#5]
A little odd... a private message:

> When I uninstall the realname module it leaves the table in the database, so when re-installing, it says "table already existing", or similar. It fails to function after that.

This should not happen, because the module defines its table via hook_schema, hence the table should get dropped automatically.

I can not reproduce it.

**Comment by steve159265** [comment]
subsequently found issue was (I believe) caused by conflict with entity-tokens ([1.x-1.1.0-beta) module. Upgrade to 1.x-2.0.0-rc1 resolved the issue. Suggest make note in Real Name documentation, module requires v2 entity-tokens (if also installed)

**Comment by indigoxela** [comment]
I see, glad you sorted things out!

The contrib modules extending the core Entity module are currently getting improved, which is very cool. I'll keep an eye on that.

**Comment by indigoxela** [comment]
A hint re Entity Token version has been added to the readme.
