### ISSUE TITLE
Deprecated function format_username

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/realname#6]
**Steps to reproduce**

1. turn drupal compatibility off:  `$settings['backdrop_drupal_compatibility'] = FALSE;` in `settings.php`
2. Setup real name as per instructions
3. Create content and attempt to change the author to another user

**Expected result**
Autocomplete works the same as it does with drupal compatibility switched off

**Actual result**
Error message:
![image](https://user-images.githubusercontent.com/20357797/159530069-f67a6b15-1171-4ffc-98f0-18868869397b.png)

```
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path:
StatusText: error
ResponseText: Error: Call to undefined function format_username() in realname_autocomplete() (line 447 of /app/docroot/modules/realname/realname.module).
```

There isn't a a drop-in backdrop equivalent listed here [this deprecation notice](https://docs.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/function/format_username/1) but the function outlined there:
```php
function format_username($account) {
  watchdog_deprecated_function('drupal', __FUNCTION__);
  return user_format_name($account);
}
```
suggests that `user_format_name` ([docs](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_format_name/1)) should be listed as a drop in replacement.

@indigoxela - if you agree that this seems the right approach, I'm happy to have a go at a PR

**Comment by indigoxela** [comment]
Oops, nice catch! How did I miss that. Should be fixed in https://github.com/backdrop-contrib/realname/commit/5cb249f92c506acb524828e2d4b2212b210706b5
