### ISSUE TITLE
Notice: Trying to access array offset on value of type null in realname_autocomplete()

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/realname#7]
This happens when editing a comment and one puts some name into it that's not an existing username.

Should not cause any notices (PHP 7.4), form validation still catches non-existing usernames, anyway.

Also happens in Drupal, see https://www.drupal.org/project/realname/issues/3263690

**Comment by echozone** [comment]
RTBC
I had this Notice using Devel's Switch user autocomplete field. This commit fixed it.

**Comment by indigoxela** [comment]
@echozone that's great, many thanks for verifying. :+1:
